# Generated by Django 6.0.4 on 2026-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Moradia', 'Moradia'), ('Saúde', 'Saúde'), ('Lazer', 'Lazer'), ('Educação', 'Educação'), ('Outros', 'Outros')], max_length=50),
        ),
    ]
